### PR TITLE
Hrushabh

### PR DESCRIPTION
**Pull request by HrushabhHirudkar**
Please Check the Schema for the database

### CODE REVIEW

**Comment by HrushabhHirudkar** [comment]
Database_Overview


DATABASE OVERVIEW

**Comment by saboonikhil** [comment]
We should add the images to README as a draft schema @jaykhatri0875 @HrushabhHirudkar

**Comment by HrushabhHirudkar** [comment]
Created a Resource folder and added the diagram there

**Comment by saboonikhil** [comment]
> Created a Resource folder and added the diagram there

I see you have updated the develop branch. Should I close this PR?

**Comment by HrushabhHirudkar** [comment]
yes you can . if anyone need the schema for table creation it is on my branch. Otherwise I can add it to the resources as well

**Pull request closed without merging**
